frontend: {enabled: false}

image:
  repository: jnorwood/hashbash-consumers-go
  tag: release-20190526-1738

configmap:
  data:
    HASHBASH_DATABASE_HOST: mysql.hashbash-components.svc.cluster.local
    HASHBASH_RABBITMQ_HOST: rabbitmq-0.rabbitmq-headless.hashbash-components.svc.cluster.local
    HASHBASH_RABBITMQ_USERNAME: user

ingress:
  enabled: false

servicemonitor:
  enabled: true
