alertmanager:
  enabled: false

coreDns:
  enabled: false

defaultRules:
  create: false

grafana:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeStateMetrics:
  enabled: false

prometheus:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: nginx

  prometheusSpec:
    image:
      tag: v2.9.2

    serviceMonitorNamespaceSelector:
      any: true

prometheusOperator:
  image:
    tag: v0.30.0

  prometheusConfigReloaderImage:
    tag: v0.30.0
