releases:
  ##
  # Cluster-level components
  ##

  # Prometheus/Grafana/Node-metrics-collection
  - name: prometheus-operator
    namespace: monitoring
    chart: stable/prometheus-operator
    version: ^5.10.1
    values:
      - global/prometheus-operator/values.yaml
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/prometheus-operator/values.yaml
    secrets:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/prometheus-operator/secrets.yaml

  # Global Ingress Controller
  - name: nginx-ingress
    namespace: web-ingress
    chart: stable/nginx-ingress
    version: ^1.6.11
    values:
      - global/nginx-ingress/values.yaml
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/nginx-ingress/values.yaml

  ##
  # Hashbash Components
  ##

  # mysql instance
  - name: mysql
    namespace: hashbash-components
    chart: stable/mysql
    version: ^1.1.1
    values:
      - global/mysql/values.yaml
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/mysql/values.yaml
    secrets:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/mysql/secrets.yaml

  # rabbitmq instance
  - name: rabbitmq
    namespace: hashbash-components
    chart: stable/rabbitmq
    version: ^5.5.2
    values:
      - global/rabbitmq/values.yaml
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/rabbitmq/values.yaml
    secrets:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/rabbitmq/secrets.yaml

  ##
  # Hashbash Webapps
  ##
  - name: hashbash-webapp-go
    namespace: hashbash
    chart: ../charts/hashbash-webapp
    values:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/hashbash-webapp-go/values.yaml
    secrets:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/hashbash-webapp-go/secrets.yaml

  - name: hashbash-webapp-java
    namespace: hashbash
    chart: ../charts/hashbash-webapp
    values:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/hashbash-webapp-java/values.yaml
    secrets:
      - {{ requiredEnv "HELMFILE_CLUSTER" }}/hashbash-webapp-java/secrets.yaml
