{{ if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
{{ toYaml .Values.secret.data | indent 2 }}
{{- end }}
