image:
  repository: jnorwood/hashbash-webapp
  tag: release-20190525-2032

configmap:
  data:
    SPRING_PROFILES_ACTIVE: LCL

    HASHBASH_DATABASE_HOST: mysql.hashbash-components.svc.cluster.local
    SPRING_RABBITMQ_USERNAME: user
    SPRING_RABBITMQ_HOST: rabbitmq-0.rabbitmq-headless.hashbash-components.svc.cluster.local

ingress:
  hosts:
    - java.hashbash.local

servicemonitor:
  enabled: true
  path: /actuator/prometheus
