frontend: {enabled: false}

image:
  repository: jnorwood/hashbash-consumers
  tag: release-20190526-1740

ports:
  management: 8082

configmap:
  data:
    SPRING_PROFILES_ACTIVE: LCL

    HASHBASH_DATABASE_HOST: mysql.hashbash-components.svc.cluster.local
    SPRING_RABBITMQ_USERNAME: user
    SPRING_RABBITMQ_HOST: rabbitmq-0.rabbitmq-headless.hashbash-components.svc.cluster.local

ingress:
  enabled: true
  hosts:
    - java.hashbash.local

servicemonitor:
  enabled: true
  path: /actuator/prometheus
