apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: management
      port: 8080
      protocol: TCP
      targetPort: management
  selector:
    app: {{ template "app.name" . }}
    release: {{ .Release.Name }}
