{
 "title": "Hashbash Webapp Metrics",
 "tags": [
  "hashbash",
  "web"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "golang_time_shift", "label": "Golang Time Shift", "query": "1s" }
  ]
 },
 "panels": [
  {
   "title": "Response Rates (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ingress, status)(rate(nginx_ingress_controller_requests{ingress=~\"hashbash-webapp-go.*\"}[1m] offset $golang_time_shift))",
     "legendFormat": "{{ingress}} - {{status}}"
    },
    {
     "expr": "sum by (ingress, status)(rate(nginx_ingress_controller_requests{ingress=~\"hashbash-webapp-java.*\"}[1m]))",
     "legendFormat": "{{ingress}} - {{status}}"
    }
   ]
  },
  {
   "title": "P50 Latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.50, sum by (le, ingress)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"hashbash-webapp-go\"}[1m] offset $golang_time_shift)))",
     "legendFormat": "{{ingress}}"
    },
    {
     "expr": "histogram_quantile(.50, sum by (le, ingress)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"hashbash-webapp-java\"}[1m])))",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"hashbash\", container_name=\"hashbash\", pod_name=~\"hashbash-webapp-go.*\"} offset $golang_time_shift)",
     "legendFormat": "hashbash-webapp-go"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"hashbash\", container_name=\"hashbash\", pod_name=~\"hashbash-webapp-java.*\"})",
     "legendFormat": "hashbash-webapp-java"
    }
   ]
  },
  {
   "title": "P99 Latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum by (le, ingress)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"hashbash-webapp-go\"}[1m] offset $golang_time_shift)))",
     "legendFormat": "{{ingress}}"
    },
    {
     "expr": "histogram_quantile(.99, sum by (le, ingress)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"hashbash-webapp-java\"}[1m])))",
     "legendFormat": "{{ingress}}"
    }
   ]
  }
 ]
}