{
 "title": "Hashbash Generation Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "golang_job_time_shift", "label": "Golang Job Time Shift", "query": "1s" }
  ]
 },
 "panels": [
  {
   "title": "Chains Generated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, batch_size, chain_length, hash_function, rainbow_table_id)(rainbow_chain_created_total{job=\"hashbash-engine-go\"} offset $golang_job_time_shift)",
     "legendFormat": "{{ job }}"
    },
    {
     "expr": "sum by (job, batch_size, chain_length, hash_function, rainbow_table_id)(rainbow_chain_created_total{job=\"hashbash-engine-java\"})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"hashbash\", container_name=\"hashbash\", pod_name=~\"hashbash-engine-go.*\"} offset $golang_job_time_shift)",
     "legendFormat": "hashbash-engine-go - memory use"
    },
    {
     "expr": "sum by (job)(jvm_memory_used_bytes{job=\"hashbash-engine-java\"})",
     "legendFormat": "{{ job }} - memory use"
    }
   ]
  },
  {
   "title": "Job Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job, batch_size, chain_length, hash_function, rainbow_table_id)(rainbow_chain_generate_seconds_sum{job=\"hashbash-engine-go\"} offset $golang_job_time_shift)",
     "legendFormat": "{{job}} - generate"
    },
    {
     "expr": "sum by (job, batch_size, chain_length, hash_function, rainbow_table_id)(rainbow_chain_generate_seconds_sum{job=\"hashbash-engine-java\"})",
     "legendFormat": "{{job}} - generate"
    },
    {
     "expr": "sum by (job, batch_size, chain_length, hash_function, rainbow_table_id)(rainbow_chain_write_seconds_sum{job=\"hashbash-engine-go\"} offset $golang_job_time_shift)",
     "legendFormat": "{{job}} - write"
    },
    {
     "expr": "sum by (job, batch_size, chain_length, hash_function, rainbow_table_id)(rainbow_chain_write_seconds_sum{job=\"hashbash-engine-java\"})",
     "legendFormat": "{{job}} - write"
    }
   ]
  }
 ]
}