frontend: {enabled: false}

image:
  repository: jnorwood/hashbash-consumers
  tag: release-20190526-1740

ports:
  management: 8082

nodeSelector: {role: engine}
tolerations:
  - key: engine
    operator: Equal
    value: "true"
    effect: "NoSchedule"
