frontend: {enabled: false}

image:
  repository: jnorwood/hashbash-consumers-go
  tag: release-20190528-1941

ingress:
  enabled: false

nodeSelector: {role: engine}
tolerations:
  - key: engine
    operator: Equal
    value: "true"
    effect: "NoSchedule"
