grafana:
  ingress:
    hosts:
      - grafana.hashbash.com

prometheus:
  ingress:
    hosts:
      - prometheus.hashbash.com

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 4Gi
